name: Hello World
author: Amir Rashkovsky
description: Some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Amir
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node16"
  main: "dist/index.js"
